name: Run shell commands
on:  [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello Security Gurus!! This is our first git hub actions workflow"